# Cleaning Customer Dataset

In [24]:
import pandas as pd

# Load the Olist customer dataset
try:
    df_customers = pd.read_csv('/olist_customers_dataset.csv')
    display(df_customers.head())
except FileNotFoundError:
    print("Error: 'olist_customers_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [25]:
df_customers.shape

(99441, 5)

In [26]:
df_customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [27]:
df_customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [28]:
# Check for duplicate rows
duplicate_rows = df_customers.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

Number of duplicate rows: 0

In [30]:
# Check for negative zip codes
negative_zip_codes = df_customers[df_customers['customer_zip_code_prefix'] < 0]

print(f"Number of rows with negative zip codes: {len(negative_zip_codes)}")

# Optionally, display the rows with negative zip codes if any are found
if not negative_zip_codes.empty:
    print("Rows with negative zip codes:")
    display(negative_zip_codes)

Number of rows with negative zip codes: 0

# Cleaning Geoloacation Dataset

In [31]:
try:
    df_geolocation = pd.read_csv('/olist_geolocation_dataset.csv')
    display(df_geolocation.head())
except FileNotFoundError:
    print("Error: 'olist_geolocation_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [22]:
df_geolocation.shape

(1000163, 5)

In [23]:
df_geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [32]:
df_geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [37]:
# Check for duplicate rows
df_geolocation.duplicated().sum()

np.int64(261831)

In [39]:
# Remove duplicate rows from df_geolocation, keeping the first occurrence
df_geolocation_cleaned = df_geolocation.drop_duplicates(keep='first')

# Display the new shape of the DataFrame
print(f"Shape of df_geolocation after removing duplicates: {df_geolocation_cleaned.shape}")

Shape of df_geolocation after removing duplicates: (738332, 5)

In [40]:
# Check for negative zip codes in df_geolocation_cleaned
negative_geo_zip_codes = df_geolocation_cleaned[df_geolocation_cleaned['geolocation_zip_code_prefix'] < 0]

print(f"Number of rows with negative geolocation zip codes: {len(negative_geo_zip_codes)}")

# Optionally, display the rows with negative zip codes if any are found
if not negative_geo_zip_codes.empty:
    print("Rows with negative geolocation zip codes:")
    display(negative_geo_zip_codes)

Number of rows with negative geolocation zip codes: 0

# Cleaning Order Items Dataset

In [41]:
try:
    df_order_items = pd.read_csv('/olist_order_items_dataset.csv')
    display(df_order_items.head())
except FileNotFoundError:
    print("Error: 'olist_order_items_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [42]:
df_order_items.shape

(112650, 7)

In [43]:
df_order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [44]:
try:
    df_order_items['shipping_limit_date'] = pd.to_datetime(df_order_items['shipping_limit_date'])
    display(df_order_items.dtypes)
except Exception as e:
    print(f"Error converting 'shipping_limit_date' to datetime: {e}")

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [45]:
df_order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [46]:
df_order_items.duplicated().sum()

np.int64(0)

In [53]:
negative_price_values = df_order_items[df_order_items['price'] < 0]
negative_freight_values = df_order_items[df_order_items['freight_value'] < 0]

print(f"Number of rows with negative price values: {len(negative_price_values)}")
print(f"Number of rows with negative freight values: {len(negative_freight_values)}")

if not negative_price_values.empty:
    print("\nRows with negative price values:")
    display(negative_price_values)

if not negative_freight_values.empty:
    print("\nRows with negative freight values:")
    display(negative_freight_values)

Number of rows with negative price values: 0
Number of rows with negative freight values: 0

# Cleaning Order Payment Dataset

In [47]:
try:
    df_order_payments = pd.read_csv('/olist_order_payments_dataset.csv')
    display(df_order_payments.head())
except FileNotFoundError:
    print("Error: 'olist_order_payments_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [48]:
df_order_payments.shape

(103886, 5)

In [49]:
df_order_payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [50]:
df_order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [51]:
df_order_payments.duplicated().sum()

np.int64(0)

In [55]:
negative_installments = df_order_payments[df_order_payments['payment_installments'] < 0]
negative_payment_values = df_order_payments[df_order_payments['payment_value'] < 0]

print(f"Number of rows with negative payment installments: {len(negative_installments)}")
print(f"Number of rows with negative payment values: {len(negative_payment_values)}")

if not negative_installments.empty:
    print("\nRows with negative payment installments:")
    display(negative_installments)

if not negative_payment_values.empty:
    print("\nRows with negative payment values:")
    display(negative_payment_values)

Number of rows with negative payment installments: 0
Number of rows with negative payment values: 0

# Cleaning Order Reviews Dataset

In [54]:
try:
    df_order_reviews = pd.read_csv('/olist_order_reviews_dataset.csv')
    display(df_order_reviews.head())
except FileNotFoundError:
    print("Error: 'olist_order_reviews_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")
df_order_reviews.shape

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

(99224, 7)

In [56]:
df_order_reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [57]:
df_order_reviews = df_order_reviews.drop(columns=['review_comment_title', 'review_comment_message'])
display(df_order_reviews.head())
display(df_order_reviews.dtypes)

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01 00:00:00,2018-03-02 10:26:53

review_id                  object
order_id                   object
review_score                int64
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [58]:
df_order_reviews['review_creation_date'] = pd.to_datetime(df_order_reviews['review_creation_date'])
df_order_reviews['review_answer_timestamp'] = pd.to_datetime(df_order_reviews['review_answer_timestamp'])
display(df_order_reviews.dtypes)

review_id                          object
order_id                           object
review_score                        int64
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [59]:
df_order_reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [60]:
df_order_reviews.duplicated().sum()

np.int64(0)

# Cleaning Orders Dataset

In [64]:
try:
    df_orders = pd.read_csv('/olist_orders_dataset.csv')
    display(df_orders.head())
except FileNotFoundError:
    print("Error: 'olist_orders_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [65]:
df_orders.shape

(99441, 8)

In [66]:
df_orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [67]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    df_orders[col] = pd.to_datetime(df_orders[col], errors='coerce')

display(df_orders.dtypes)

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [68]:
df_orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [69]:
df_orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [70]:
df_orders[df_orders['order_approved_at'].isnull()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [136]:
df_orders[(df_orders['order_approved_at'].isnull()) & (df_orders['order_status'] == 'delivered')]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [72]:
df_orders.loc[
    (df_orders['order_approved_at'].isnull()) &
    (df_orders['order_status'] == 'delivered'),
    'order_approved_at'
] = df_orders['order_purchase_timestamp']

df_orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 146
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [73]:
print('Order status for missing order_delivered_carrier_date:')
display(df_orders[df_orders['order_delivered_carrier_date'].isnull()]['order_status'].value_counts())

print('\nOrder status for missing order_delivered_customer_date:')
display(df_orders[df_orders['order_delivered_customer_date'].isnull()]['order_status'].value_counts())

Order status for missing order_delivered_carrier_date:

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

Order status for missing order_delivered_customer_date:

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [74]:
# Impute missing order_delivered_carrier_date for 'delivered' orders
df_orders.loc[
    (df_orders['order_delivered_carrier_date'].isnull()) &
    (df_orders['order_status'] == 'delivered'),
    'order_delivered_carrier_date'
] = df_orders['order_approved_at']

# Impute missing order_delivered_customer_date for 'delivered' orders
df_orders.loc[
    (df_orders['order_delivered_customer_date'].isnull()) &
    (df_orders['order_status'] == 'delivered'),
    'order_delivered_customer_date'
] = df_orders['order_delivered_carrier_date']

display(df_orders.isnull().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 146
order_delivered_carrier_date     1781
order_delivered_customer_date    2957
order_estimated_delivery_date       0
dtype: int64

In [76]:
inconsistent_delivery_data = df_orders[
    (df_orders['order_approved_at'].isnull()) &
    (
        (df_orders['order_delivered_carrier_date'].notnull()) |
        (df_orders['order_delivered_customer_date'].notnull())
    )
]

print(f"Number of inconsistent entries: {len(inconsistent_delivery_data)}")

if not inconsistent_delivery_data.empty:
    print("Inconsistent entries where order_approved_at is null but a delivery date is present:")
    display(inconsistent_delivery_data)

Number of inconsistent entries: 0

In [77]:
inconsistent_carrier_delivery_data = df_orders[
    (df_orders['order_delivered_carrier_date'].isnull()) &
    (df_orders['order_delivered_customer_date'].notnull())
]

print(f"Number of inconsistent entries: {len(inconsistent_carrier_delivery_data)}")

if not inconsistent_carrier_delivery_data.empty:
    print("Inconsistent entries where order_delivered_carrier_date is null but order_delivered_customer_date is present:")
    display(inconsistent_carrier_delivery_data)

Number of inconsistent entries: 0

In [75]:
df_orders.duplicated().sum()

np.int64(0)

# Cleaning Product Dataset

In [78]:
try:
    df_products = pd.read_csv('/olist_products_dataset.csv')
    display(df_products.head())
except FileNotFoundError:
    print("Error: 'olist_products_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [79]:
df_products.shape

(32951, 9)

In [80]:
df_products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [81]:
df_products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [85]:
df_products[(df_products['product_category_name'].isnull()) & (df_products['product_name_lenght'].isnull()) & (df_products['product_description_lenght'].isnull()) & (df_products['product_photos_qty'].isnull()) ]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [86]:
df_products_cleaned = df_products.dropna(subset=['product_weight_g'])
print(f"Shape of df_products after dropping rows with null product_weight_g: {df_products_cleaned.shape}")

display(df_products_cleaned.isnull().sum())

Shape of df_products after dropping rows with null product_weight_g: (32949, 9)

product_id                      0
product_category_name         609
product_name_lenght           609
product_description_lenght    609
product_photos_qty            609
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
dtype: int64

In [87]:
df_products_cleaned = df_products_cleaned.dropna(subset=['product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty'])

print(f"Shape of df_products after dropping rows with null product description details: {df_products_cleaned.shape}")

display(df_products_cleaned.isnull().sum())

Shape of df_products after dropping rows with null product description details: (32340, 9)

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [88]:
df_products_cleaned.duplicated().sum()

np.int64(0)

# Cleaning Sellers Dataset

In [89]:
try:
    df_sellers = pd.read_csv('/olist_sellers_dataset.csv')
    display(df_sellers.head())
except FileNotFoundError:
    print("Error: 'olist_sellers_dataset.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [90]:
df_sellers.shape

(3095, 4)

In [91]:
df_sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [92]:
df_sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [93]:
df_sellers.duplicated().sum()

np.int64(0)

In [94]:
try:
    df_product_category_name_translation = pd.read_csv('/product_category_name_translation.csv')
    display(df_product_category_name_translation.head())
except FileNotFoundError:
    print("Error: 'product_category_name_translation.csv' not found. Please upload the file or provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [95]:
print(f"Shape of df_product_category_name_translation: {df_product_category_name_translation.shape}")

Shape of df_product_category_name_translation: (71, 2)

In [96]:
df_product_category_name_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [97]:
df_product_category_name_translation.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [98]:
df_product_category_name_translation.duplicated().sum()

np.int64(0)

In [99]:
# Merge df_products_cleaned with df_product_category_name_translation
df_products_cleaned = pd.merge(
    df_products_cleaned,
    df_product_category_name_translation,
    on='product_category_name',
    how='left'
)
display(df_products_cleaned.head())

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [100]:
# Drop the original 'product_category_name' column and rename the English column
df_products_cleaned = df_products_cleaned.drop(columns=['product_category_name'])
df_products_cleaned = df_products_cleaned.rename(columns={'product_category_name_english': 'product_category_name'})

display(df_products_cleaned.head())
display(df_products_cleaned.dtypes)

,product_id,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

product_id                     object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
product_category_name          object
dtype: object

In [105]:
# Check for nulls in the new product_category_name, as some categories might not have a translation
df_products_cleaned.isnull().sum()

product_id                    0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
product_category_name         0
dtype: int64

## Renaming DataFrames with `_cleaned` Suffix

In [106]:
# Renaming df_customers
df_customers_cleaned = df_customers.copy()

# Renaming df_order_items
df_order_items_cleaned = df_order_items.copy()

# Renaming df_order_payments
df_order_payments_cleaned = df_order_payments.copy()

# Renaming df_order_reviews
df_order_reviews_cleaned = df_order_reviews.copy()

# Renaming df_orders
df_orders_cleaned = df_orders.copy()

# Renaming df_sellers
df_sellers_cleaned = df_sellers.copy()

# Renaming df_product_category_name_translation
df_product_category_name_translation_cleaned = df_product_category_name_translation.copy()

print("All specified DataFrames have been renamed with a '_cleaned' suffix.")

All specified DataFrames have been renamed with a '_cleaned' suffix.

## Final Cleaned Datasets Overview

### 1. Customers Data (`df_customers_cleaned`)

In [107]:
print('df_customers_cleaned Head:')
display(df_customers_cleaned.head())
print('\ndf_customers_cleaned Shape:')
display(df_customers_cleaned.shape)

df_customers_cleaned Head:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

df_customers_cleaned Shape:

(99441, 5)

### 2. Geolocation Data (`df_geolocation_cleaned`)

In [108]:
print('df_geolocation_cleaned Head:')
display(df_geolocation_cleaned.head())
print('\ndf_geolocation_cleaned Shape:')
display(df_geolocation_cleaned.shape)

df_geolocation_cleaned Head:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

df_geolocation_cleaned Shape:

(738332, 5)

### 3. Order Items Data (`df_order_items_cleaned`)

In [109]:
print('df_order_items_cleaned Head:')
display(df_order_items_cleaned.head())
print('\ndf_order_items_cleaned Shape:')
display(df_order_items_cleaned.shape)

df_order_items_cleaned Head:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

df_order_items_cleaned Shape:

(112650, 7)

### 4. Order Payments Data (`df_order_payments_cleaned`)

In [110]:
print('df_order_payments_cleaned Head:')
display(df_order_payments_cleaned.head())
print('\ndf_order_payments_cleaned Shape:')
display(df_order_payments_cleaned.shape)

df_order_payments_cleaned Head:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

df_order_payments_cleaned Shape:

(103886, 5)

### 5. Order Reviews Data (`df_order_reviews_cleaned`)

In [111]:
print('df_order_reviews_cleaned Head:')
display(df_order_reviews_cleaned.head())
print('\ndf_order_reviews_cleaned Shape:')
display(df_order_reviews_cleaned.shape)

df_order_reviews_cleaned Head:

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01,2018-03-02 10:26:53

df_order_reviews_cleaned Shape:

(99224, 5)

### 6. Orders Data (`df_orders_cleaned`)

In [112]:
print('df_orders_cleaned Head:')
display(df_orders_cleaned.head())
print('\ndf_orders_cleaned Shape:')
display(df_orders_cleaned.shape)

df_orders_cleaned Head:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

df_orders_cleaned Shape:

(99441, 8)

### 7. Products Data (`df_products_cleaned`)

In [113]:
print('df_products_cleaned Head:')
display(df_products_cleaned.head())
print('\ndf_products_cleaned Shape:')
display(df_products_cleaned.shape)

df_products_cleaned Head:

,product_id,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

df_products_cleaned Shape:

(32327, 9)

### 8. Sellers Data (`df_sellers_cleaned`)

In [114]:
print('df_sellers_cleaned Head:')
display(df_sellers_cleaned.head())
print('\ndf_sellers_cleaned Shape:')
display(df_sellers_cleaned.shape)

df_sellers_cleaned Head:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

df_sellers_cleaned Shape:

(3095, 4)

### 9. Product Category Name Translation Data (`df_product_category_name_translation_cleaned`)

In [115]:
print('df_product_category_name_translation_cleaned Head:')
display(df_product_category_name_translation_cleaned.head())
print('\ndf_product_category_name_translation_cleaned Shape:')
display(df_product_category_name_translation_cleaned.shape)

df_product_category_name_translation_cleaned Head:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

df_product_category_name_translation_cleaned Shape:

(71, 2)

## Download Cleaned Datasets

In [116]:
df_customers_cleaned.to_csv('customers_cleaned.csv', index=False)
print('df_customers_cleaned.csv saved successfully.')

df_customers_cleaned.csv saved successfully.

In [117]:
df_geolocation_cleaned.to_csv('geolocation_cleaned.csv', index=False)
print('df_geolocation_cleaned.csv saved successfully.')

df_geolocation_cleaned.csv saved successfully.

In [118]:
df_order_items_cleaned.to_csv('order_items_cleaned.csv', index=False)
print('df_order_items_cleaned.csv saved successfully.')

df_order_items_cleaned.csv saved successfully.

In [119]:
df_order_payments_cleaned.to_csv('order_payments_cleaned.csv', index=False)
print('df_order_payments_cleaned.csv saved successfully.')

df_order_payments_cleaned.csv saved successfully.

In [120]:
df_order_reviews_cleaned.to_csv('order_reviews_cleaned.csv', index=False)
print('df_order_reviews_cleaned.csv saved successfully.')

df_order_reviews_cleaned.csv saved successfully.

In [121]:
df_orders_cleaned.to_csv('orders_cleaned.csv', index=False)
print('df_orders_cleaned.csv saved successfully.')

df_orders_cleaned.csv saved successfully.

In [122]:
df_products_cleaned.to_csv('products_cleaned.csv', index=False)
print('df_products_cleaned.csv saved successfully.')

df_products_cleaned.csv saved successfully.

In [123]:
df_sellers_cleaned.to_csv('sellers_cleaned.csv', index=False)
print('df_sellers_cleaned.csv saved successfully.')

df_sellers_cleaned.csv saved successfully.

In [124]:
!ls -l

total 100144
-rw-r--r-- 1 root root  8562270 Jun 23 13:25 customers_cleaned.csv
-rw-r--r-- 1 root root 43333586 Jun 23 13:25 geolocation_cleaned.csv
-rw-r--r-- 1 root root 14911576 Jun 23 13:25 order_items_cleaned.csv
-rw-r--r-- 1 root root  5633362 Jun 23 13:25 order_payments_cleaned.csv
-rw-r--r-- 1 root root 10716269 Jun 23 13:25 order_reviews_cleaned.csv
-rw-r--r-- 1 root root 16512371 Jun 23 13:25 orders_cleaned.csv
-rw-r--r-- 1 root root  2694102 Jun 23 13:25 products_cleaned.csv
drwxr-xr-x 1 root root     4096 Jun  4 13:32 sample_data
-rw-r--r-- 1 root root   163590 Jun 23 13:25 sellers_cleaned.csv

In [134]:
from google.colab import files

# Download a specific file, for example, the last one we tried to save
try:
    files.download('sellers_cleaned.csv')
    print('product_category_name_translation_cleaned.csv downloaded successfully.')
except Exception as e:
    print(f"Error downloading file: {e}. Please ensure the file exists.")

product_category_name_translation_cleaned.csv downloaded successfully.